---

- name: install bird package
  package:
    name: bird
    state: present

- name: bird config file
  template:
    src: bird.conf.j2
    dest: /etc/bird/bird.conf
    mode: '0644'
  register: bird_config_file

- name: ensure bird service is running
  service:
    name: bird
    state: started
    enabled: true

- name: restart service when config is changed
  service:
    name: bird
    state: restarted
  when: bird_config_file.changed

- name: install kubectl
  snap:
    name:
      - kubectl
    classic: yes

- name: download calicoctl
  get_url:
    url: https://github.com/projectcalico/calicoctl/releases/download/v3.16.1/calicoctl
    dest: /usr/local/bin/calicoctl
    mode: 0755
